# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    container_name: stockDb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:
    expose:
      # Opens port 3306 on the container
      - '3306'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'